name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out the repo
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --Dockerfile --tag chamodshehanka/node-test:$(date +%s)

    - name: Build and push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/docker101tutorial
