on: push
name: PhpUnit prueba de test
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # For YAML Actions, use v1 or later
      - uses: pxgamer/phpunit-action@master
        with:
          # If there isn't a PHPUnit config, specify files or directories to test
          command: test/CalculadoraTest.php
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
  
  push_to_registry:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
      - uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build
        run: docker build . --Dockerfile --tag chamodshehanka/node-test:$(date +%s)

      - name: Build and push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/docker101tutorial