on: push
name: PhpUnit prueba de test
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # For YAML Actions, use v1 or later
      - uses: pxgamer/phpunit-action@master
        with:
          # If there isn't a PHPUnit config, specify files or directories to test
          command: test/CalculadoraTest.php
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out the repo
      
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build image
        run: docker build -t localhost:8000/ramonpradas/docker_publish_github:0.0.1 .

      - name: Docker Push
        run: docker push localhost:8000/${{secrets.DOCKER_USER}}/docker_publish_github